#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Apr 04, 2020 10:44:24 PM EDT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 875x732+470+124
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab52 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Label 
    vTcl:DefineAlias "$top.lab52" "Label2" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex53 \
        -background white -font TkTextFont -foreground black -height 24 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 124 -wrap word 
    $top.tex53 configure -font "TkTextFont"
    $top.tex53 insert end text
    vTcl:DefineAlias "$top.tex53" "Text2" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu56 \
        -takefocus {} -text Tbutton 
    vTcl:DefineAlias "$top.tBu56" "TButton2" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $top.tLa57 \
        -text Tlabelframe -width 850 -height 595 
    vTcl:DefineAlias "$top.tLa57" "TLabelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tLa57
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr58 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 505 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 835 
    vTcl:DefineAlias "$site_3_0.scr58" "Scrolledtext1" vTcl:WidgetProc "Toplevel1" 1

    $site_3_0.scr58.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu59 \
        -takefocus {} -text Tbutton 
    vTcl:DefineAlias "$site_3_0.tBu59" "TButton3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.scr58 \
        -in $site_3_0 -x 10 -y 20 -width 835 -relwidth 0 -height 505 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu59 \
        -in $site_3_0 -x 390 -y 540 -anchor nw -bordermode ignore 
    text $top.tex62 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 124 -wrap word 
    $top.tex62 configure -font "TkTextFont"
    $top.tex62 insert end text
    vTcl:DefineAlias "$top.tex62" "Text1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab63 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$top.lab63" "Label1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton $top.tCh68 \
        -variable tch68 -takefocus {} -text Tcheck 
    vTcl:DefineAlias "$top.tCh68" "TCheckbutton1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab52 \
        -in $top -x 30 -y 80 -width 214 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex53 \
        -in $top -x 290 -y 80 -width 124 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu56 \
        -in $top -x 450 -y 80 -anchor nw -bordermode ignore 
    place $top.tLa57 \
        -in $top -x 10 -y 130 -width 850 -relwidth 0 -height 595 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex62 \
        -in $top -x 290 -y 40 -width 124 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.lab63 \
        -in $top -x 30 -y 40 -width 214 -relwidth 0 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.tCh68 \
        -in $top -x 680 -y 100 -width 140 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

